import type { ModelEntry } from '../../../types/director';

// ---------------------------------------------------------------------------
// Helper preset objects
// ---------------------------------------------------------------------------

export const ASPECT_RATIOS = {
  '1:1': { width: 1024, height: 1024 },
  '16:9': { width: 1344, height: 768 },
  '9:16': { width: 768, height: 1344 },
  '4:3': { width: 1152, height: 896 },
  '3:4': { width: 896, height: 1152 },
  '3:2': { width: 1216, height: 832 },
  '2:3': { width: 832, height: 1216 },
  '21:9': { width: 1536, height: 640 },
} as const;

export const QUALITY_PRESETS = {
  draft: { label: 'Draft', steps: 10, cfg: 5 },
  standard: { label: 'Standard', steps: 25, cfg: 7 },
  high: { label: 'High', steps: 40, cfg: 7.5 },
  ultra: { label: 'Ultra', steps: 60, cfg: 8 },
} as const;

export const STYLE_PRESETS = [
  'none',
  'cinematic',
  'anime',
  'photographic',
  'digital_art',
  'comic_book',
  'fantasy',
  'neon_punk',
  'isometric',
  'origami',
  '3d_model',
  'pixel_art',
] as const;

export const VIDEO_DURATIONS = [2, 4, 5, 6, 8, 10] as const; // seconds

// ---------------------------------------------------------------------------
// Active model ids (V1 launch)
// ---------------------------------------------------------------------------

const ACTIVE_IDS = new Set([
  // Image: Generate from text
  'flux-2-pro', 'flux-2-flex', 'flux-2-dev-lora', 'flux-fast',
  'flux-pro-1-1', 'flux-pro-1-1-ultra', 'flux-dev-lora',
  'reve', 'mystic', 'recraft-v4', 'recraft-v3',
  'gpt-image-1-5', 'seedream-v4', 'seedream-v5',
  'nano-banana-2', 'nano-banana-pro', 'qwen-image', 'z-image-turbo',
  // Image: Edit / Kontext
  'flux-kontext', 'flux-kontext-lora', 'flux-kontext-multi-image',
  'flux-fill-pro', 'flux-2-max', 'gpt-image-1-5-edit',
  'qwen-image-edit-plus', 'seedream-v4-5-edit', 'seedream-v5-edit',
  'relight-2-0', 'replace-background', 'bria-remove-background',
  // Image: From image
  'flux-dev-redux', 'flux-canny-pro', 'flux-depth-pro', 'flux-controlnet-lora',
  // Image: Enhance
  'topaz-image-upscale', 'topaz-sharpen', 'magnific-upscale', 'recraft-crisp-upscale',
  // Image: Vector
  'recraft-vectorizer', 'recraft-v3-svg',
  // Video: Generate
  'wan-2-5', 'wan-2-2', 'wan-video', 'ltx-2-video',
  'kling-video', 'kling-1-6', 'kling-3', 'kling-o3-edit-video',
  'veo-3-1-text', 'sora-2', 'pixverse-v4-5',
  'seedance-v1-5-pro', 'moonvalley', 'hunyuan', 'grok-imagine-video',
  // Video: Lip sync
  'omnihuman-v1-5', 'sync-2-pro',
  // Video: Enhance
  'topaz-video-upscaler', 'real-esrgan-video-upscaler',
  // 3D
  'trellis-3d-v2', 'meshy-v6',
]);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function status(id: string): 'active' | 'coming_soon' | 'internal_only' {
  return ACTIVE_IDS.has(id) ? 'active' : 'coming_soon';
}

// ---------------------------------------------------------------------------
// MODEL CATALOG
// ---------------------------------------------------------------------------

export const MODEL_CATALOG: ModelEntry[] = [
  // =========================================================================
  // IMAGE MODELS > Generate from text
  // =========================================================================
  {
    id: 'flux-2-dev-lora',
    provider: 'fal',
    displayName: 'Flux 2 Dev LoRA',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('flux-2-dev-lora'),
    capabilities: ['text-to-image', 'lora'],
    defaultParams: { width: 1024, height: 1024, steps: 28, guidance: 3.5 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'flux-2-pro',
    provider: 'fal',
    displayName: 'Flux 2 Pro',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('flux-2-pro'),
    capabilities: ['text-to-image', 'high-quality'],
    defaultParams: { width: 1024, height: 1024, steps: 30, guidance: 3.5 },
    creditCost: 5,
    badge: null,
  },
  {
    id: 'flux-2-flex',
    provider: 'fal',
    displayName: 'Flux 2 Flex',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('flux-2-flex'),
    capabilities: ['text-to-image', 'flexible-resolution'],
    defaultParams: { width: 1024, height: 1024, steps: 25, guidance: 3.5 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'reve',
    provider: 'fal',
    displayName: 'Reve',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('reve'),
    capabilities: ['text-to-image'],
    defaultParams: { width: 1024, height: 1024, steps: 30, guidance: 7 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'higgsfield-image',
    provider: 'higgsfield',
    displayName: 'Higgsfield Image',
    icon: 'higgsfield',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('higgsfield-image'),
    capabilities: ['text-to-image'],
    defaultParams: { width: 1024, height: 1024, steps: 30 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'gpt-image-1-5',
    provider: 'openai',
    displayName: 'GPT Image 1.5',
    icon: 'openai',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('gpt-image-1-5'),
    capabilities: ['text-to-image', 'high-quality'],
    defaultParams: { width: 1024, height: 1024, quality: 'standard' },
    creditCost: 4,
    badge: null,
  },
  {
    id: 'imagen-4',
    provider: 'google',
    displayName: 'Imagen 4',
    icon: 'google',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('imagen-4'),
    capabilities: ['text-to-image', 'high-quality'],
    defaultParams: { width: 1024, height: 1024 },
    creditCost: 5,
    badge: null,
  },
  {
    id: 'imagen-3',
    provider: 'google',
    displayName: 'Imagen 3',
    icon: 'google',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('imagen-3'),
    capabilities: ['text-to-image', 'high-quality'],
    defaultParams: { width: 1024, height: 1024 },
    creditCost: 4,
    badge: null,
  },
  {
    id: 'imagen-3-fast',
    provider: 'google',
    displayName: 'Imagen 3 Fast',
    icon: 'google',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('imagen-3-fast'),
    capabilities: ['text-to-image', 'fast'],
    defaultParams: { width: 1024, height: 1024 },
    creditCost: 2,
    badge: null,
  },
  {
    id: 'flux-pro-1-1-ultra',
    provider: 'fal',
    displayName: 'Flux Pro 1.1 Ultra',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('flux-pro-1-1-ultra'),
    capabilities: ['text-to-image', 'ultra-high-res'],
    defaultParams: { width: 2048, height: 2048, steps: 40, guidance: 3.5 },
    creditCost: 5,
    badge: null,
  },
  {
    id: 'flux-pro-1-1',
    provider: 'fal',
    displayName: 'Flux Pro 1.1',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('flux-pro-1-1'),
    capabilities: ['text-to-image', 'high-quality'],
    defaultParams: { width: 1024, height: 1024, steps: 30, guidance: 3.5 },
    creditCost: 4,
    badge: null,
  },
  {
    id: 'flux-fast',
    provider: 'fal',
    displayName: 'Flux Fast',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('flux-fast'),
    capabilities: ['text-to-image', 'fast'],
    defaultParams: { width: 1024, height: 1024, steps: 4, guidance: 3.5 },
    creditCost: 1,
    badge: null,
  },
  {
    id: 'flux-dev-lora',
    provider: 'fal',
    displayName: 'Flux Dev LoRA',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('flux-dev-lora'),
    capabilities: ['text-to-image', 'lora'],
    defaultParams: { width: 1024, height: 1024, steps: 28, guidance: 3.5 },
    creditCost: 2,
    badge: null,
  },
  {
    id: 'recraft-v4',
    provider: 'recraft',
    displayName: 'Recraft V4',
    icon: 'recraft',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('recraft-v4'),
    capabilities: ['text-to-image', 'design', 'high-quality'],
    defaultParams: { width: 1024, height: 1024, style: 'photographic' },
    creditCost: 4,
    badge: 'New',
  },
  {
    id: 'recraft-v3',
    provider: 'recraft',
    displayName: 'Recraft V3',
    icon: 'recraft',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('recraft-v3'),
    capabilities: ['text-to-image', 'design'],
    defaultParams: { width: 1024, height: 1024, style: 'photographic' },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'mystic',
    provider: 'fal',
    displayName: 'Mystic',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('mystic'),
    capabilities: ['text-to-image'],
    defaultParams: { width: 1024, height: 1024, steps: 30 },
    creditCost: 2,
    badge: null,
  },
  {
    id: 'ideogram-v3',
    provider: 'ideogram',
    displayName: 'Ideogram V3',
    icon: 'ideogram',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('ideogram-v3'),
    capabilities: ['text-to-image', 'text-rendering'],
    defaultParams: { width: 1024, height: 1024 },
    creditCost: 4,
    badge: null,
  },
  {
    id: 'ideogram-v3-character',
    provider: 'ideogram',
    displayName: 'Ideogram V3 Character',
    icon: 'ideogram',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('ideogram-v3-character'),
    capabilities: ['text-to-image', 'character-design'],
    defaultParams: { width: 1024, height: 1024 },
    creditCost: 4,
    badge: null,
  },
  {
    id: 'stable-diffusion-3-5',
    provider: 'stability',
    displayName: 'Stable Diffusion 3.5',
    icon: 'stability',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('stable-diffusion-3-5'),
    capabilities: ['text-to-image'],
    defaultParams: { width: 1024, height: 1024, steps: 28, cfg: 7 },
    creditCost: 2,
    badge: null,
  },
  {
    id: 'minimax-image-01',
    provider: 'minimax',
    displayName: 'Minimax Image 01',
    icon: 'minimax',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('minimax-image-01'),
    capabilities: ['text-to-image'],
    defaultParams: { width: 1024, height: 1024 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'bria',
    provider: 'bria',
    displayName: 'Bria',
    icon: 'bria',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('bria'),
    capabilities: ['text-to-image', 'commercial-safe'],
    defaultParams: { width: 1024, height: 1024, steps: 30 },
    creditCost: 2,
    badge: null,
  },
  {
    id: 'luma-photon',
    provider: 'luma',
    displayName: 'Luma Photon',
    icon: 'luma',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('luma-photon'),
    capabilities: ['text-to-image'],
    defaultParams: { width: 1024, height: 1024 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'nvidia-sana',
    provider: 'nvidia',
    displayName: 'Nvidia Sana',
    icon: 'nvidia',
    category: 'Image Models',
    subcategory: 'Generate from text',
    status: status('nvidia-sana'),
    capabilities: ['text-to-image', 'fast'],
    defaultParams: { width: 1024, height: 1024, steps: 20 },
    creditCost: 2,
    badge: null,
  },

  // =========================================================================
  // IMAGE MODELS > Generate vector graphics
  // =========================================================================
  {
    id: 'recraft-vectorizer',
    provider: 'recraft',
    displayName: 'Recraft Vectorizer',
    icon: 'recraft',
    category: 'Image Models',
    subcategory: 'Generate vector graphics',
    status: status('recraft-vectorizer'),
    capabilities: ['image-to-svg', 'vectorize'],
    defaultParams: {},
    creditCost: 3,
    badge: 'New',
  },
  {
    id: 'vectorizer',
    provider: 'fal',
    displayName: 'Vectorizer',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate vector graphics',
    status: status('vectorizer'),
    capabilities: ['image-to-svg', 'vectorize'],
    defaultParams: {},
    creditCost: 2,
    badge: null,
  },
  {
    id: 'recraft-v3-svg',
    provider: 'recraft',
    displayName: 'Recraft V3 SVG',
    icon: 'recraft',
    category: 'Image Models',
    subcategory: 'Generate vector graphics',
    status: status('recraft-v3-svg'),
    capabilities: ['text-to-svg', 'vector-generation'],
    defaultParams: { width: 1024, height: 1024 },
    creditCost: 4,
    badge: null,
  },
  {
    id: 'text-to-vector',
    provider: 'fal',
    displayName: 'Text To Vector',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate vector graphics',
    status: status('text-to-vector'),
    capabilities: ['text-to-svg'],
    defaultParams: {},
    creditCost: 3,
    badge: null,
  },

  // =========================================================================
  // IMAGE MODELS > Edit images
  // =========================================================================
  {
    id: 'nano-banana-2',
    provider: 'fal',
    displayName: 'Nano Banana 2',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('nano-banana-2'),
    capabilities: ['image-editing', 'instruction-based'],
    defaultParams: {},
    creditCost: 3,
    badge: 'New',
  },
  {
    id: 'flux-2-max',
    provider: 'fal',
    displayName: 'Flux 2 Max',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('flux-2-max'),
    capabilities: ['image-editing', 'high-quality'],
    defaultParams: { steps: 30, guidance: 3.5 },
    creditCost: 6,
    badge: null,
  },
  {
    id: 'seedream-v4-5-edit',
    provider: 'fal',
    displayName: 'Seedream V4.5 Edit',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('seedream-v4-5-edit'),
    capabilities: ['image-editing'],
    defaultParams: {},
    creditCost: 4,
    badge: null,
  },
  {
    id: 'seedream-v5-edit',
    provider: 'fal',
    displayName: 'Seedream V5 Edit',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('seedream-v5-edit'),
    capabilities: ['image-editing', 'high-quality'],
    defaultParams: {},
    creditCost: 5,
    badge: 'New',
  },
  {
    id: 'nano-banana-pro',
    provider: 'fal',
    displayName: 'Nano Banana Pro',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('nano-banana-pro'),
    capabilities: ['image-editing', 'instruction-based'],
    defaultParams: {},
    creditCost: 4,
    badge: null,
  },
  {
    id: 'qwen-image-edit-plus',
    provider: 'fal',
    displayName: 'Qwen Image Edit Plus',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('qwen-image-edit-plus'),
    capabilities: ['image-editing'],
    defaultParams: {},
    creditCost: 3,
    badge: null,
  },
  {
    id: 'reve-edit',
    provider: 'fal',
    displayName: 'Reve Edit',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('reve-edit'),
    capabilities: ['image-editing'],
    defaultParams: {},
    creditCost: 3,
    badge: null,
  },
  {
    id: 'nano-banana',
    provider: 'fal',
    displayName: 'Nano Banana',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('nano-banana'),
    capabilities: ['image-editing', 'instruction-based'],
    defaultParams: {},
    creditCost: 2,
    badge: null,
  },
  {
    id: 'runway-gen-4-image',
    provider: 'runway',
    displayName: 'Runway Gen-4 Image',
    icon: 'runway',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('runway-gen-4-image'),
    capabilities: ['image-editing'],
    defaultParams: {},
    creditCost: 5,
    badge: null,
  },
  {
    id: 'flux-kontext',
    provider: 'fal',
    displayName: 'Flux Kontext',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('flux-kontext'),
    capabilities: ['image-editing', 'context-aware'],
    defaultParams: { steps: 28, guidance: 3.5 },
    creditCost: 4,
    badge: null,
  },
  {
    id: 'flux-kontext-lora',
    provider: 'fal',
    displayName: 'Flux Kontext LoRA',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('flux-kontext-lora'),
    capabilities: ['image-editing', 'context-aware', 'lora'],
    defaultParams: { steps: 28, guidance: 3.5 },
    creditCost: 4,
    badge: null,
  },
  {
    id: 'gpt-image-1-5-edit',
    provider: 'openai',
    displayName: 'GPT Image 1.5 Edit',
    icon: 'openai',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('gpt-image-1-5-edit'),
    capabilities: ['image-editing', 'instruction-based'],
    defaultParams: { quality: 'standard' },
    creditCost: 5,
    badge: null,
  },
  {
    id: 'flux-kontext-multi-image',
    provider: 'fal',
    displayName: 'Flux Kontext Multi Image',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('flux-kontext-multi-image'),
    capabilities: ['image-editing', 'multi-image', 'context-aware'],
    defaultParams: { steps: 28, guidance: 3.5 },
    creditCost: 5,
    badge: null,
  },
  {
    id: 'seededit-3-0',
    provider: 'fal',
    displayName: 'SeedEdit 3.0',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('seededit-3-0'),
    capabilities: ['image-editing'],
    defaultParams: {},
    creditCost: 4,
    badge: null,
  },
  {
    id: 'flux-fill-pro',
    provider: 'fal',
    displayName: 'Flux Fill Pro',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('flux-fill-pro'),
    capabilities: ['inpainting', 'fill'],
    defaultParams: { steps: 30, guidance: 3.5 },
    creditCost: 4,
    badge: null,
  },
  {
    id: 'flux-2-inpaint-klein-9b',
    provider: 'fal',
    displayName: 'Flux 2 Inpaint Klein 9B',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('flux-2-inpaint-klein-9b'),
    capabilities: ['inpainting'],
    defaultParams: { steps: 28, guidance: 3.5 },
    creditCost: 3,
    badge: 'New',
  },
  {
    id: 'flux-dev-lora-inpaint',
    provider: 'fal',
    displayName: 'Flux Dev LoRA Inpaint',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('flux-dev-lora-inpaint'),
    capabilities: ['inpainting', 'lora'],
    defaultParams: { steps: 28, guidance: 3.5 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'ideogram-v3-inpaint',
    provider: 'ideogram',
    displayName: 'Ideogram V3 Inpaint',
    icon: 'ideogram',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('ideogram-v3-inpaint'),
    capabilities: ['inpainting', 'text-rendering'],
    defaultParams: {},
    creditCost: 5,
    badge: null,
  },
  {
    id: 'ideogram-v2-inpaint',
    provider: 'ideogram',
    displayName: 'Ideogram V2 Inpaint',
    icon: 'ideogram',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('ideogram-v2-inpaint'),
    capabilities: ['inpainting'],
    defaultParams: {},
    creditCost: 4,
    badge: null,
  },
  {
    id: 'sd3-inpaint',
    provider: 'stability',
    displayName: 'SD3 Inpaint',
    icon: 'stability',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('sd3-inpaint'),
    capabilities: ['inpainting'],
    defaultParams: { steps: 28, cfg: 7 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'bria-inpaint',
    provider: 'bria',
    displayName: 'Bria Inpaint',
    icon: 'bria',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('bria-inpaint'),
    capabilities: ['inpainting', 'commercial-safe'],
    defaultParams: {},
    creditCost: 3,
    badge: null,
  },
  {
    id: 'flux-pro-outpaint',
    provider: 'fal',
    displayName: 'Flux Pro Outpaint',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('flux-pro-outpaint'),
    capabilities: ['outpainting'],
    defaultParams: { steps: 30, guidance: 3.5 },
    creditCost: 5,
    badge: null,
  },
  {
    id: 'sd3-outpaint',
    provider: 'stability',
    displayName: 'SD3 Outpaint',
    icon: 'stability',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('sd3-outpaint'),
    capabilities: ['outpainting'],
    defaultParams: { steps: 28, cfg: 7 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'sd3-remove-background',
    provider: 'stability',
    displayName: 'SD3 Remove Background',
    icon: 'stability',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('sd3-remove-background'),
    capabilities: ['background-removal'],
    defaultParams: {},
    creditCost: 2,
    badge: null,
  },
  {
    id: 'bria-remove-background',
    provider: 'bria',
    displayName: 'Bria Remove Background',
    icon: 'bria',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('bria-remove-background'),
    capabilities: ['background-removal', 'commercial-safe'],
    defaultParams: {},
    creditCost: 2,
    badge: null,
  },
  {
    id: 'sd3-content-aware-fill',
    provider: 'stability',
    displayName: 'SD3 Content-Aware Fill',
    icon: 'stability',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('sd3-content-aware-fill'),
    capabilities: ['content-aware-fill'],
    defaultParams: {},
    creditCost: 3,
    badge: null,
  },
  {
    id: 'bria-content-aware-fill',
    provider: 'bria',
    displayName: 'Bria Content-Aware Fill',
    icon: 'bria',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('bria-content-aware-fill'),
    capabilities: ['content-aware-fill', 'commercial-safe'],
    defaultParams: {},
    creditCost: 3,
    badge: null,
  },
  {
    id: 'kolors-virtual-try-on',
    provider: 'fal',
    displayName: 'Kolors Virtual Try On',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('kolors-virtual-try-on'),
    capabilities: ['virtual-try-on', 'image-editing'],
    defaultParams: {},
    creditCost: 5,
    badge: null,
  },
  {
    id: 'replace-background',
    provider: 'fal',
    displayName: 'Replace Background',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('replace-background'),
    capabilities: ['background-replacement'],
    defaultParams: {},
    creditCost: 3,
    badge: null,
  },
  {
    id: 'bria-replace-background',
    provider: 'bria',
    displayName: 'Bria Replace Background',
    icon: 'bria',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('bria-replace-background'),
    capabilities: ['background-replacement', 'commercial-safe'],
    defaultParams: {},
    creditCost: 3,
    badge: null,
  },
  {
    id: 'relight-2-0',
    provider: 'fal',
    displayName: 'Relight 2.0',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('relight-2-0'),
    capabilities: ['relighting', 'image-editing'],
    defaultParams: {},
    creditCost: 4,
    badge: null,
  },
  {
    id: 'qwen-image-edit-2511',
    provider: 'fal',
    displayName: 'Qwen Image Edit 2511',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Edit images',
    status: status('qwen-image-edit-2511'),
    capabilities: ['image-editing', 'instruction-based'],
    defaultParams: {},
    creditCost: 3,
    badge: 'New',
  },

  // =========================================================================
  // IMAGE MODELS > Generate from image
  // =========================================================================
  {
    id: 'qwen-edit-multiangle',
    provider: 'fal',
    displayName: 'Qwen Edit Multiangle',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from image',
    status: status('qwen-edit-multiangle'),
    capabilities: ['image-to-image', 'multi-angle'],
    defaultParams: {},
    creditCost: 4,
    badge: null,
  },
  {
    id: 'flux-dev-redux',
    provider: 'fal',
    displayName: 'Flux Dev Redux',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from image',
    status: status('flux-dev-redux'),
    capabilities: ['image-to-image', 'style-transfer'],
    defaultParams: { steps: 28, guidance: 3.5 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'flux-controlnet-lora',
    provider: 'fal',
    displayName: 'Flux ControlNet & LoRA',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from image',
    status: status('flux-controlnet-lora'),
    capabilities: ['image-to-image', 'controlnet', 'lora'],
    defaultParams: { steps: 28, guidance: 3.5 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'flux-canny-pro',
    provider: 'fal',
    displayName: 'Flux Canny Pro',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from image',
    status: status('flux-canny-pro'),
    capabilities: ['image-to-image', 'canny-edge'],
    defaultParams: { steps: 30, guidance: 3.5 },
    creditCost: 4,
    badge: null,
  },
  {
    id: 'flux-depth-pro',
    provider: 'fal',
    displayName: 'Flux Depth Pro',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Generate from image',
    status: status('flux-depth-pro'),
    capabilities: ['image-to-image', 'depth-map'],
    defaultParams: { steps: 30, guidance: 3.5 },
    creditCost: 4,
    badge: null,
  },
  {
    id: 'image-to-image',
    provider: 'stability',
    displayName: 'Image To Image',
    icon: 'stability',
    category: 'Image Models',
    subcategory: 'Generate from image',
    status: status('image-to-image'),
    capabilities: ['image-to-image'],
    defaultParams: { steps: 28, cfg: 7, strength: 0.7 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'sd-controlnets',
    provider: 'stability',
    displayName: 'Stable Diffusion Controlnets',
    icon: 'stability',
    category: 'Image Models',
    subcategory: 'Generate from image',
    status: status('sd-controlnets'),
    capabilities: ['image-to-image', 'controlnet'],
    defaultParams: { steps: 28, cfg: 7 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'sketch-to-image',
    provider: 'stability',
    displayName: 'Sketch to Image',
    icon: 'stability',
    category: 'Image Models',
    subcategory: 'Generate from image',
    status: status('sketch-to-image'),
    capabilities: ['sketch-to-image'],
    defaultParams: { steps: 28, cfg: 7 },
    creditCost: 3,
    badge: null,
  },

  // =========================================================================
  // IMAGE MODELS > Enhance images
  // =========================================================================
  {
    id: 'topaz-image-upscale',
    provider: 'topaz',
    displayName: 'Topaz Image Upscale',
    icon: 'topaz',
    category: 'Image Models',
    subcategory: 'Enhance images',
    status: status('topaz-image-upscale'),
    capabilities: ['upscale', 'enhance'],
    defaultParams: { scale: 2 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'topaz-sharpen',
    provider: 'topaz',
    displayName: 'Topaz Sharpen',
    icon: 'topaz',
    category: 'Image Models',
    subcategory: 'Enhance images',
    status: status('topaz-sharpen'),
    capabilities: ['sharpen', 'enhance'],
    defaultParams: { strength: 0.5 },
    creditCost: 2,
    badge: null,
  },
  {
    id: 'magnific-skin-enhancer',
    provider: 'fal',
    displayName: 'Magnific Skin Enhancer',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Enhance images',
    status: status('magnific-skin-enhancer'),
    capabilities: ['skin-enhance', 'face-enhance'],
    defaultParams: {},
    creditCost: 4,
    badge: null,
  },
  {
    id: 'magnific-upscale',
    provider: 'fal',
    displayName: 'Magnific Upscale',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Enhance images',
    status: status('magnific-upscale'),
    capabilities: ['upscale', 'enhance', 'creative-upscale'],
    defaultParams: { scale: 2 },
    creditCost: 5,
    badge: null,
  },
  {
    id: 'magnific-precision-upscale',
    provider: 'fal',
    displayName: 'Magnific Precision Upscale',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Enhance images',
    status: status('magnific-precision-upscale'),
    capabilities: ['upscale', 'enhance', 'precision'],
    defaultParams: { scale: 2 },
    creditCost: 5,
    badge: null,
  },
  {
    id: 'magnific-precision-upscale-v2',
    provider: 'fal',
    displayName: 'Magnific Precision Upscale V2',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Enhance images',
    status: status('magnific-precision-upscale-v2'),
    capabilities: ['upscale', 'enhance', 'precision'],
    defaultParams: { scale: 2 },
    creditCost: 5,
    badge: null,
  },
  {
    id: 'enhancor-image-upscale',
    provider: 'fal',
    displayName: 'Enhancor Image Upscale',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Enhance images',
    status: status('enhancor-image-upscale'),
    capabilities: ['upscale', 'enhance'],
    defaultParams: { scale: 2 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'enhancor-realistic-skin',
    provider: 'fal',
    displayName: 'Enhancor Realistic Skin',
    icon: 'fal',
    category: 'Image Models',
    subcategory: 'Enhance images',
    status: status('enhancor-realistic-skin'),
    capabilities: ['skin-enhance', 'face-enhance'],
    defaultParams: {},
    creditCost: 3,
    badge: null,
  },
  {
    id: 'recraft-crisp-upscale',
    provider: 'recraft',
    displayName: 'Recraft Crisp Upscale',
    icon: 'recraft',
    category: 'Image Models',
    subcategory: 'Enhance images',
    status: status('recraft-crisp-upscale'),
    capabilities: ['upscale', 'enhance', 'crisp'],
    defaultParams: { scale: 2 },
    creditCost: 3,
    badge: null,
  },

  // =========================================================================
  // VIDEO MODELS > Generate from text or image
  // =========================================================================
  {
    id: 'grok-imagine-video',
    provider: 'fal',
    displayName: 'Grok Imagine Video',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('grok-imagine-video'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 20,
    badge: null,
  },
  {
    id: 'veo-3-1-text-to-video',
    provider: 'google',
    displayName: 'Veo 3.1 Text to Video',
    icon: 'google',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('veo-3-1-text-to-video'),
    capabilities: ['text-to-video', 'high-quality'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 30,
    badge: null,
  },
  {
    id: 'veo-3-1-image-to-video',
    provider: 'google',
    displayName: 'Veo 3.1 Image to Video',
    icon: 'google',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('veo-3-1-image-to-video'),
    capabilities: ['image-to-video', 'high-quality'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 30,
    badge: null,
  },
  {
    id: 'seedance-v1-5-pro',
    provider: 'fal',
    displayName: 'Seedance V1.5 Pro',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('seedance-v1-5-pro'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 20,
    badge: null,
  },
  {
    id: 'sora-2',
    provider: 'openai',
    displayName: 'Sora 2',
    icon: 'openai',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('sora-2'),
    capabilities: ['text-to-video', 'image-to-video', 'high-quality'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 25,
    badge: null,
  },
  {
    id: 'ltx-2-video',
    provider: 'fal',
    displayName: 'LTX 2 Video',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('ltx-2-video'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'higgsfield-video',
    provider: 'higgsfield',
    displayName: 'Higgsfield Video',
    icon: 'higgsfield',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('higgsfield-video'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'wan-2-5',
    provider: 'fal',
    displayName: 'Wan 2.5',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('wan-2-5'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'wan-2-2',
    provider: 'fal',
    displayName: 'Wan 2.2',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('wan-2-2'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 12,
    badge: null,
  },
  {
    id: 'moonvalley',
    provider: 'fal',
    displayName: 'Moonvalley',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('moonvalley'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'seedance-v1-0',
    provider: 'fal',
    displayName: 'Seedance V1.0',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('seedance-v1-0'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'pixverse-v4-5',
    provider: 'fal',
    displayName: 'Pixverse V4.5',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('pixverse-v4-5'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'runway-gen-4',
    provider: 'runway',
    displayName: 'Runway Gen-4',
    icon: 'runway',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('runway-gen-4'),
    capabilities: ['text-to-video', 'image-to-video', 'high-quality'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 20,
    badge: null,
  },
  {
    id: 'runway-gen-4-turbo',
    provider: 'runway',
    displayName: 'Runway Gen-4 Turbo',
    icon: 'runway',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('runway-gen-4-turbo'),
    capabilities: ['text-to-video', 'image-to-video', 'fast'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'runway-gen-4-5',
    provider: 'runway',
    displayName: 'Runway Gen-4.5',
    icon: 'runway',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('runway-gen-4-5'),
    capabilities: ['text-to-video', 'image-to-video', 'high-quality'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 25,
    badge: null,
  },
  {
    id: 'runway-gen-3-turbo',
    provider: 'runway',
    displayName: 'Runway Gen-3 Turbo',
    icon: 'runway',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('runway-gen-3-turbo'),
    capabilities: ['text-to-video', 'image-to-video', 'fast'],
    defaultParams: { duration: 4, fps: 24 },
    creditCost: 10,
    badge: null,
  },
  {
    id: 'kling-3',
    provider: 'kling',
    displayName: 'Kling 3',
    icon: 'kling',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('kling-3'),
    capabilities: ['text-to-video', 'image-to-video', 'high-quality'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 25,
    badge: 'New',
  },
  {
    id: 'kling-1-6',
    provider: 'kling',
    displayName: 'Kling 1.6',
    icon: 'kling',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('kling-1-6'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'kling-video',
    provider: 'kling',
    displayName: 'Kling Video',
    icon: 'kling',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('kling-video'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 12,
    badge: null,
  },
  {
    id: 'kling-first-last-frame',
    provider: 'kling',
    displayName: 'Kling First & Last Frame',
    icon: 'kling',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('kling-first-last-frame'),
    capabilities: ['image-to-video', 'keyframe-control'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 18,
    badge: null,
  },
  {
    id: 'minimax-hailuo-02',
    provider: 'minimax',
    displayName: 'Minimax Hailuo-02',
    icon: 'minimax',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('minimax-hailuo-02'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 18,
    badge: null,
  },
  {
    id: 'veo-2',
    provider: 'google',
    displayName: 'Veo 2',
    icon: 'google',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('veo-2'),
    capabilities: ['text-to-video', 'image-to-video', 'high-quality'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 20,
    badge: null,
  },
  {
    id: 'minimax-video-director',
    provider: 'minimax',
    displayName: 'Minimax Video Director',
    icon: 'minimax',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('minimax-video-director'),
    capabilities: ['text-to-video', 'image-to-video', 'camera-control'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 20,
    badge: null,
  },
  {
    id: 'minimax-video-01',
    provider: 'minimax',
    displayName: 'Minimax Video 01',
    icon: 'minimax',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('minimax-video-01'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'luma-ray-2',
    provider: 'luma',
    displayName: 'Luma Ray 2',
    icon: 'luma',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('luma-ray-2'),
    capabilities: ['text-to-video', 'image-to-video', 'high-quality'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 18,
    badge: null,
  },
  {
    id: 'luma-ray-2-flash',
    provider: 'luma',
    displayName: 'Luma Ray 2 Flash',
    icon: 'luma',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('luma-ray-2-flash'),
    capabilities: ['text-to-video', 'image-to-video', 'fast'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 10,
    badge: null,
  },
  {
    id: 'hunyuan',
    provider: 'fal',
    displayName: 'Hunyuan',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('hunyuan'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'wan-video',
    provider: 'fal',
    displayName: 'Wan Video',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from text or image',
    status: status('wan-video'),
    capabilities: ['text-to-video', 'image-to-video'],
    defaultParams: { duration: 5, fps: 24 },
    creditCost: 12,
    badge: null,
  },

  // =========================================================================
  // VIDEO MODELS > Generate from video
  // =========================================================================
  {
    id: 'grok-imagine-video-edit',
    provider: 'fal',
    displayName: 'Grok Imagine Video edit',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('grok-imagine-video-edit'),
    capabilities: ['video-to-video', 'video-editing'],
    defaultParams: { fps: 24 },
    creditCost: 18,
    badge: null,
  },
  {
    id: 'ltx-2-video-to-video',
    provider: 'fal',
    displayName: 'LTX 2 Video to Video',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('ltx-2-video-to-video'),
    capabilities: ['video-to-video'],
    defaultParams: { fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'kling-o3-edit-video',
    provider: 'kling',
    displayName: 'Kling o3 Edit Video',
    icon: 'kling',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('kling-o3-edit-video'),
    capabilities: ['video-to-video', 'video-editing'],
    defaultParams: { fps: 24 },
    creditCost: 18,
    badge: null,
  },
  {
    id: 'kling-motion-control',
    provider: 'kling',
    displayName: 'Kling Motion Control',
    icon: 'kling',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('kling-motion-control'),
    capabilities: ['video-to-video', 'motion-control'],
    defaultParams: { fps: 24 },
    creditCost: 18,
    badge: 'New',
  },
  {
    id: 'kling-o1-edit-video',
    provider: 'kling',
    displayName: 'Kling o1 Edit Video',
    icon: 'kling',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('kling-o1-edit-video'),
    capabilities: ['video-to-video', 'video-editing'],
    defaultParams: { fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'kling-o1-reference-v2v',
    provider: 'kling',
    displayName: 'Kling o1 Reference Video to Video',
    icon: 'kling',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('kling-o1-reference-v2v'),
    capabilities: ['video-to-video', 'reference-guided'],
    defaultParams: { fps: 24 },
    creditCost: 18,
    badge: null,
  },
  {
    id: 'runway-aleph',
    provider: 'runway',
    displayName: 'Runway Aleph',
    icon: 'runway',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('runway-aleph'),
    capabilities: ['video-to-video', 'video-editing'],
    defaultParams: { fps: 24 },
    creditCost: 20,
    badge: null,
  },
  {
    id: 'runway-act-two',
    provider: 'runway',
    displayName: 'Runway Act-Two',
    icon: 'runway',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('runway-act-two'),
    capabilities: ['video-to-video', 'performance-transfer'],
    defaultParams: { fps: 24 },
    creditCost: 20,
    badge: null,
  },
  {
    id: 'luma-reframe',
    provider: 'luma',
    displayName: 'Luma Reframe',
    icon: 'luma',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('luma-reframe'),
    capabilities: ['video-to-video', 'reframe'],
    defaultParams: { fps: 24 },
    creditCost: 10,
    badge: null,
  },
  {
    id: 'luma-modify',
    provider: 'luma',
    displayName: 'Luma Modify',
    icon: 'luma',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('luma-modify'),
    capabilities: ['video-to-video', 'video-editing'],
    defaultParams: { fps: 24 },
    creditCost: 12,
    badge: null,
  },
  {
    id: 'wan-2-2-animate-replace',
    provider: 'fal',
    displayName: 'Wan 2.2 Animate Replace',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('wan-2-2-animate-replace'),
    capabilities: ['video-to-video', 'object-replacement'],
    defaultParams: { fps: 24 },
    creditCost: 12,
    badge: null,
  },
  {
    id: 'wan-2-2-animate-move',
    provider: 'fal',
    displayName: 'Wan 2.2 Animate Move',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('wan-2-2-animate-move'),
    capabilities: ['video-to-video', 'motion-transfer'],
    defaultParams: { fps: 24 },
    creditCost: 12,
    badge: null,
  },
  {
    id: 'wan-vace-depth',
    provider: 'fal',
    displayName: 'Wan Vace Depth',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('wan-vace-depth'),
    capabilities: ['video-to-video', 'depth-guided'],
    defaultParams: { fps: 24 },
    creditCost: 12,
    badge: null,
  },
  {
    id: 'wan-vace-pose',
    provider: 'fal',
    displayName: 'Wan Vace Pose',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('wan-vace-pose'),
    capabilities: ['video-to-video', 'pose-guided'],
    defaultParams: { fps: 24 },
    creditCost: 12,
    badge: null,
  },
  {
    id: 'wan-vace-reframe',
    provider: 'fal',
    displayName: 'Wan Vace Reframe',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('wan-vace-reframe'),
    capabilities: ['video-to-video', 'reframe'],
    defaultParams: { fps: 24 },
    creditCost: 10,
    badge: null,
  },
  {
    id: 'wan-vace-outpaint',
    provider: 'fal',
    displayName: 'Wan Vace Outpaint',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('wan-vace-outpaint'),
    capabilities: ['video-to-video', 'outpainting'],
    defaultParams: { fps: 24 },
    creditCost: 12,
    badge: null,
  },
  {
    id: 'hunyuan-video-to-video',
    provider: 'fal',
    displayName: 'Hunyuan Video to Video',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Generate from video',
    status: status('hunyuan-video-to-video'),
    capabilities: ['video-to-video'],
    defaultParams: { fps: 24 },
    creditCost: 15,
    badge: null,
  },

  // =========================================================================
  // VIDEO MODELS > Lip sync
  // =========================================================================
  {
    id: 'omnihuman-v1-5',
    provider: 'fal',
    displayName: 'Omnihuman V1.5',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Lip sync',
    status: status('omnihuman-v1-5'),
    capabilities: ['lip-sync', 'audio-driven'],
    defaultParams: { fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'sync-2-pro',
    provider: 'fal',
    displayName: 'Sync 2 Pro',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Lip sync',
    status: status('sync-2-pro'),
    capabilities: ['lip-sync', 'audio-driven'],
    defaultParams: { fps: 24 },
    creditCost: 12,
    badge: null,
  },
  {
    id: 'kling-ai-avatar',
    provider: 'kling',
    displayName: 'Kling AI Avatar',
    icon: 'kling',
    category: 'Video Models',
    subcategory: 'Lip sync',
    status: status('kling-ai-avatar'),
    capabilities: ['lip-sync', 'avatar', 'audio-driven'],
    defaultParams: { fps: 24 },
    creditCost: 15,
    badge: null,
  },
  {
    id: 'pixverse-lipsync',
    provider: 'fal',
    displayName: 'Pixverse Lipsync',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Lip sync',
    status: status('pixverse-lipsync'),
    capabilities: ['lip-sync', 'audio-driven'],
    defaultParams: { fps: 24 },
    creditCost: 10,
    badge: null,
  },

  // =========================================================================
  // VIDEO MODELS > Enhance videos
  // =========================================================================
  {
    id: 'topaz-video-upscaler',
    provider: 'topaz',
    displayName: 'Topaz Video Upscaler',
    icon: 'topaz',
    category: 'Video Models',
    subcategory: 'Enhance videos',
    status: status('topaz-video-upscaler'),
    capabilities: ['video-upscale', 'enhance'],
    defaultParams: { scale: 2 },
    creditCost: 5,
    badge: null,
  },
  {
    id: 'bria-upscale',
    provider: 'bria',
    displayName: 'Bria Upscale',
    icon: 'bria',
    category: 'Video Models',
    subcategory: 'Enhance videos',
    status: status('bria-upscale'),
    capabilities: ['video-upscale', 'enhance', 'commercial-safe'],
    defaultParams: { scale: 2 },
    creditCost: 4,
    badge: null,
  },
  {
    id: 'real-esrgan-video-upscaler',
    provider: 'fal',
    displayName: 'Real-ESRGAN Video Upscaler',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Enhance videos',
    status: status('real-esrgan-video-upscaler'),
    capabilities: ['video-upscale', 'enhance'],
    defaultParams: { scale: 2 },
    creditCost: 3,
    badge: null,
  },
  {
    id: 'video-smoother',
    provider: 'fal',
    displayName: 'Video Smoother',
    icon: 'fal',
    category: 'Video Models',
    subcategory: 'Enhance videos',
    status: status('video-smoother'),
    capabilities: ['frame-interpolation', 'enhance'],
    defaultParams: { targetFps: 60 },
    creditCost: 3,
    badge: null,
  },

  // =========================================================================
  // 3D MODELS > Generate from text or image
  // =========================================================================
  {
    id: 'meshy-v6',
    provider: 'fal',
    displayName: 'Meshy V6',
    icon: 'fal',
    category: '3D Models',
    subcategory: 'Generate from text or image',
    status: status('meshy-v6'),
    capabilities: ['text-to-3d', 'image-to-3d'],
    defaultParams: {},
    creditCost: 20,
    badge: null,
  },
  {
    id: 'sam-3d-objects',
    provider: 'fal',
    displayName: 'SAM 3D Objects',
    icon: 'fal',
    category: '3D Models',
    subcategory: 'Generate from text or image',
    status: status('sam-3d-objects'),
    capabilities: ['image-to-3d', 'segmentation'],
    defaultParams: {},
    creditCost: 15,
    badge: null,
  },
  {
    id: 'rodin-v2',
    provider: 'fal',
    displayName: 'Rodin V2',
    icon: 'fal',
    category: '3D Models',
    subcategory: 'Generate from text or image',
    status: status('rodin-v2'),
    capabilities: ['text-to-3d', 'image-to-3d', 'high-quality'],
    defaultParams: {},
    creditCost: 25,
    badge: null,
  },
  {
    id: 'rodin',
    provider: 'fal',
    displayName: 'Rodin',
    icon: 'fal',
    category: '3D Models',
    subcategory: 'Generate from text or image',
    status: status('rodin'),
    capabilities: ['text-to-3d', 'image-to-3d'],
    defaultParams: {},
    creditCost: 20,
    badge: null,
  },
  {
    id: 'hunyuan-3d-v3',
    provider: 'fal',
    displayName: 'Hunyuan 3D V3',
    icon: 'fal',
    category: '3D Models',
    subcategory: 'Generate from text or image',
    status: status('hunyuan-3d-v3'),
    capabilities: ['text-to-3d', 'image-to-3d', 'high-quality'],
    defaultParams: {},
    creditCost: 25,
    badge: null,
  },
  {
    id: 'hunyuan-3d-v2-1',
    provider: 'fal',
    displayName: 'Hunyuan 3D V2.1',
    icon: 'fal',
    category: '3D Models',
    subcategory: 'Generate from text or image',
    status: status('hunyuan-3d-v2-1'),
    capabilities: ['text-to-3d', 'image-to-3d'],
    defaultParams: {},
    creditCost: 20,
    badge: null,
  },
  {
    id: 'hunyuan-3d-v2-0',
    provider: 'fal',
    displayName: 'Hunyuan 3D V2.0',
    icon: 'fal',
    category: '3D Models',
    subcategory: 'Generate from text or image',
    status: status('hunyuan-3d-v2-0'),
    capabilities: ['text-to-3d', 'image-to-3d'],
    defaultParams: {},
    creditCost: 18,
    badge: null,
  },
  {
    id: 'trellis-3d-v2',
    provider: 'fal',
    displayName: 'Trellis 3D V2',
    icon: 'fal',
    category: '3D Models',
    subcategory: 'Generate from text or image',
    status: status('trellis-3d-v2'),
    capabilities: ['text-to-3d', 'image-to-3d'],
    defaultParams: {},
    creditCost: 18,
    badge: null,
  },

  // =========================================================================
  // CUSTOM MODELS > Community models (empty for V1)
  // =========================================================================
];
