import type { NodeRegistryEntry, NodeIOPort } from '../../../types/director';

// ─── Reusable port definitions ───────────────────────────────────────────────

const PORT = {
  textIn:      (id = 'prompt'): NodeIOPort => ({ id, label: 'Prompt', kind: 'text', required: true }),
  textOut:     (id = 'text'): NodeIOPort => ({ id, label: 'Text', kind: 'text' }),
  imageIn:     (id = 'image'): NodeIOPort => ({ id, label: 'Image', kind: 'image' }),
  imageOut:    (id = 'image'): NodeIOPort => ({ id, label: 'Image', kind: 'image' }),
  videoIn:     (id = 'video'): NodeIOPort => ({ id, label: 'Video', kind: 'video' }),
  videoOut:    (id = 'video'): NodeIOPort => ({ id, label: 'Video', kind: 'video' }),
  anyIn:       (id = 'input'): NodeIOPort => ({ id, label: 'Input', kind: 'any' }),
  anyOut:      (id = 'output'): NodeIOPort => ({ id, label: 'Output', kind: 'any' }),
  brandIn:     (): NodeIOPort => ({ id: 'brand', label: 'Brand', kind: 'brand_context', required: false }),
  campaignIn:  (): NodeIOPort => ({ id: 'campaign', label: 'Campaign', kind: 'campaign_context', required: false }),
  productIn:   (): NodeIOPort => ({ id: 'product', label: 'Product', kind: 'product_context', required: false }),
  audienceIn:  (): NodeIOPort => ({ id: 'audience', label: 'Audience', kind: 'audience_context' }),
  negPromptIn: (): NodeIOPort => ({ id: 'negative_prompt', label: 'Negative Prompt', kind: 'text', required: false }),
  refImageIn:  (): NodeIOPort => ({ id: 'reference_image', label: 'Reference Image', kind: 'image', required: false }),
  refVideoIn:  (): NodeIOPort => ({ id: 'reference_video', label: 'Reference Video', kind: 'video', required: false }),
} as const;

// ─── Node Registry ───────────────────────────────────────────────────────────

export const NODE_REGISTRY: NodeRegistryEntry[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // QUICK ACCESS (core utility nodes)
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'creative_direction',
    category: 'quick_access',
    displayName: 'Creative Direction',
    description: 'Structured creative direction with auto-optimization, quality scoring, shot design, and continuity control',
    icon: 'Sparkles',
    status: 'active',
    inputs: [],
    outputs: [
      PORT.textOut('prompt'),
      { id: 'negative_prompt', label: 'Negative Prompt', kind: 'text' },
    ],
    defaultData: {
      concept: '', subject: '', wardrobe: '', environment: '', mood: 'cinematic',
      lighting: 'natural, soft', composition: '', shotType: 'medium_shot',
      cameraAngle: 'eye_level', cameraMovement: 'static', realismLevel: 8,
      artisticDirection: '', brandTone: '', negativePrompt: '', text: '',
    },
    inspectorFields: [],
  },
  {
    type: 'prompt',
    category: 'quick_access',
    displayName: 'Prompt',
    description: 'Text prompt with variable support',
    icon: 'Type',
    status: 'active',
    inputs: [],
    outputs: [PORT.textOut('prompt')],
    defaultData: { text: '', negative_prompt: '', variables: [] },
    inspectorFields: [
      { key: 'text', label: 'Prompt', type: 'textarea' },
      { key: 'negative_prompt', label: 'Negative Prompt', type: 'textarea' },
    ],
  },
  {
    type: 'import',
    category: 'quick_access',
    displayName: 'Import',
    description: 'Import image or video from file or CRM assets',
    icon: 'Download',
    status: 'active',
    inputs: [],
    outputs: [PORT.anyOut('output')],
    defaultData: { source: 'upload', asset_id: null, url: '' },
    inspectorFields: [
      { key: 'source', label: 'Source', type: 'select', options: [{ label: 'Upload', value: 'upload' }, { label: 'CRM Asset', value: 'asset' }, { label: 'URL', value: 'url' }] },
    ],
  },
  {
    type: 'export',
    category: 'quick_access',
    displayName: 'Export',
    description: 'Export output to file or CRM assets',
    icon: 'Upload',
    status: 'active',
    inputs: [PORT.anyIn('input')],
    outputs: [],
    defaultData: { format: 'png', quality: 90, save_to_assets: true },
    inspectorFields: [
      { key: 'format', label: 'Format', type: 'select', options: [{ label: 'PNG', value: 'png' }, { label: 'JPEG', value: 'jpeg' }, { label: 'WebP', value: 'webp' }, { label: 'MP4', value: 'mp4' }] },
      { key: 'quality', label: 'Quality', type: 'slider', min: 1, max: 100, step: 1, defaultValue: 90 },
      { key: 'save_to_assets', label: 'Save to CRM Assets', type: 'toggle', defaultValue: true },
    ],
  },
  {
    type: 'preview',
    category: 'quick_access',
    displayName: 'Preview',
    description: 'Preview image, video, or text',
    icon: 'Eye',
    status: 'active',
    inputs: [PORT.anyIn('input')],
    outputs: [],
    defaultData: {},
  },
  {
    type: 'import_model',
    category: 'quick_access',
    displayName: 'Import Model',
    description: 'Import a custom model checkpoint by URL',
    icon: 'Download',
    status: 'active',
    inputs: [],
    outputs: [PORT.anyOut('model')],
    defaultData: { model_url: '' },
    inspectorFields: [
      { key: 'model_url', label: 'Model URL', type: 'text' },
    ],
  },
  {
    type: 'import_lora',
    category: 'quick_access',
    displayName: 'Import LoRA',
    description: 'Import a LoRA adapter by URL (HuggingFace, Civitai, etc.)',
    icon: 'Download',
    status: 'active',
    inputs: [],
    outputs: [PORT.anyOut('lora')],
    defaultData: { lora_url: '', strength: 0.8 },
    inspectorFields: [
      { key: 'lora_url', label: 'LoRA URL', type: 'text' },
      { key: 'strength', label: 'Strength', type: 'slider', min: 0, max: 1.5, step: 0.05, defaultValue: 0.8 },
    ],
  },
  {
    type: 'import_multiple_loras',
    category: 'quick_access',
    displayName: 'Import Multiple LoRAs',
    description: 'Import multiple LoRA adapters',
    icon: 'Download',
    status: 'active',
    inputs: [],
    outputs: [PORT.anyOut('loras')],
    defaultData: { loras: [] },
  },
  {
    type: 'kling_o3_edit_video',
    category: 'quick_access',
    displayName: 'Kling o3 Edit Video',
    description: 'Edit video using Kling o3',
    icon: 'Video',
    status: 'active',
    inputs: [PORT.videoIn(), PORT.textIn()],
    outputs: [PORT.videoOut()],
    defaultData: { provider: 'fal', model: 'kling-o3-edit' },
    providerBound: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // TOOLS > Editing
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'levels',
    category: 'tools',
    subcategory: 'Editing',
    displayName: 'Levels',
    description: 'Adjust brightness, contrast, and saturation',
    icon: 'SlidersHorizontal',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.imageOut()],
    defaultData: { brightness: 0, contrast: 0, saturation: 0 },
  },
  {
    type: 'compositor',
    category: 'tools',
    subcategory: 'Editing',
    displayName: 'Compositor',
    description: 'Composite foreground and background layers',
    icon: 'Layers',
    status: 'active',
    inputs: [PORT.imageIn('foreground'), PORT.imageIn('background')],
    outputs: [PORT.imageOut()],
    defaultData: { blend_mode: 'normal', opacity: 1 },
  },
  {
    type: 'painter',
    category: 'tools',
    subcategory: 'Editing',
    displayName: 'Painter',
    description: 'Paint or draw on an image',
    icon: 'Paintbrush',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.imageOut()],
    defaultData: {},
  },
  {
    type: 'crop',
    category: 'tools',
    subcategory: 'Editing',
    displayName: 'Crop',
    description: 'Crop an image to a specified region',
    icon: 'Crop',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.imageOut()],
    defaultData: { x: 0, y: 0, width: 512, height: 512 },
  },
  {
    type: 'resize',
    category: 'tools',
    subcategory: 'Editing',
    displayName: 'Resize',
    description: 'Resize an image to target dimensions',
    icon: 'Maximize2',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.imageOut()],
    defaultData: { width: 1024, height: 1024, maintain_aspect: true },
  },
  {
    type: 'blur',
    category: 'tools',
    subcategory: 'Editing',
    displayName: 'Blur',
    description: 'Apply blur effect to an image',
    icon: 'Circle',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.imageOut()],
    defaultData: { radius: 5, type: 'gaussian' },
  },
  {
    type: 'invert',
    category: 'tools',
    subcategory: 'Editing',
    displayName: 'Invert',
    description: 'Invert the colors of an image',
    icon: 'CircleHalf',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.imageOut()],
    defaultData: {},
  },
  {
    type: 'channels',
    category: 'tools',
    subcategory: 'Editing',
    displayName: 'Channels',
    description: 'Extract or manipulate color channels',
    icon: 'Blend',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.imageOut()],
    defaultData: { channel: 'all' },
  },
  {
    type: 'extract_video_frame',
    category: 'tools',
    subcategory: 'Editing',
    displayName: 'Extract Video Frame',
    description: 'Extract a single frame from a video',
    icon: 'Film',
    status: 'active',
    inputs: [PORT.videoIn()],
    outputs: [PORT.imageOut()],
    defaultData: { frame_index: 0 },
  },
  {
    type: 'video_concatenator',
    category: 'tools',
    subcategory: 'Editing',
    displayName: 'Video Concatenator',
    description: 'Concatenate two video clips',
    icon: 'ListVideo',
    status: 'active',
    inputs: [PORT.videoIn('video_a'), PORT.videoIn('video_b')],
    outputs: [PORT.videoOut()],
    defaultData: {},
  },

  // ══════════════════════════════════════════════════════════════════════════
  // TOOLS > Matte
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'mask_extractor',
    category: 'tools',
    subcategory: 'Matte',
    displayName: 'Mask Extractor',
    description: 'Extract a mask from an image',
    icon: 'Scan',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.imageOut('mask')],
    defaultData: { provider: 'fal', model: 'mask-extractor' },
    providerBound: true,
  },
  {
    type: 'mask_by_text',
    category: 'tools',
    subcategory: 'Matte',
    displayName: 'Mask by Text',
    description: 'Generate a mask from a text description',
    icon: 'Scan',
    status: 'active',
    inputs: [PORT.imageIn(), PORT.textIn()],
    outputs: [PORT.imageOut('mask')],
    defaultData: { provider: 'fal', model: 'mask-by-text' },
    providerBound: true,
  },
  {
    type: 'matte_grow_shrink',
    category: 'tools',
    subcategory: 'Matte',
    displayName: 'Matte Grow / Shrink',
    description: 'Grow or shrink a matte region',
    icon: 'Scaling',
    status: 'active',
    inputs: [PORT.imageIn('mask')],
    outputs: [PORT.imageOut('mask')],
    defaultData: { amount: 0 },
  },
  {
    type: 'merge_alpha',
    category: 'tools',
    subcategory: 'Matte',
    displayName: 'Merge Alpha',
    description: 'Merge a foreground with a mask alpha channel',
    icon: 'RefreshCw',
    status: 'active',
    inputs: [PORT.imageIn('foreground'), PORT.imageIn('mask')],
    outputs: [PORT.imageOut()],
    defaultData: {},
  },
  {
    type: 'video_matte',
    category: 'tools',
    subcategory: 'Matte',
    displayName: 'Video Matte',
    description: 'Apply matte extraction to a video',
    icon: 'Film',
    status: 'active',
    inputs: [PORT.videoIn()],
    outputs: [PORT.videoOut()],
    defaultData: { provider: 'fal', model: 'video-matte' },
    providerBound: true,
  },
  {
    type: 'video_mask_by_text',
    category: 'tools',
    subcategory: 'Matte',
    displayName: 'Video Mask by Text',
    description: 'Generate a video mask from a text description',
    icon: 'Film',
    status: 'active',
    inputs: [PORT.videoIn(), PORT.textIn()],
    outputs: [PORT.videoOut()],
    defaultData: { provider: 'fal', model: 'video-matte' },
    providerBound: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // TOOLS > Text tools
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'prompt_concatenator',
    category: 'tools',
    subcategory: 'Text tools',
    displayName: 'Prompt Concatenator',
    description: 'Concatenate two text inputs with a separator',
    icon: 'TextCursorInput',
    status: 'active',
    inputs: [PORT.textIn('text_a'), PORT.textIn('text_b')],
    outputs: [PORT.textOut()],
    defaultData: { separator: ' ' },
  },
  // ── Text Overlay ─────
  {
    type: 'text_overlay',
    category: 'tools',
    subcategory: 'Editing',
    displayName: 'Text Overlay',
    description: 'Add text overlay on an image (caption, watermark, title)',
    icon: 'Type',
    status: 'active',
    inputs: [PORT.imageIn(), PORT.textIn('text')],
    outputs: [PORT.imageOut()],
    defaultData: {
      text: 'Your text here',
      font_size: 48,
      font_color: '#ffffff',
      font_weight: 'bold',
      position: 'bottom-center',
      background: 'rgba(0,0,0,0.5)',
      padding: 16,
    },
    inspectorFields: [
      { key: 'text', label: 'Text', type: 'textarea' },
      { key: 'font_size', label: 'Font Size', type: 'number', min: 12, max: 200, step: 2, defaultValue: 48 },
      { key: 'font_color', label: 'Font Color', type: 'text' },
      { key: 'font_weight', label: 'Weight', type: 'select', options: [
        { label: 'Normal', value: 'normal' }, { label: 'Bold', value: 'bold' },
      ]},
      { key: 'position', label: 'Position', type: 'select', options: [
        { label: 'Top Left', value: 'top-left' }, { label: 'Top Center', value: 'top-center' }, { label: 'Top Right', value: 'top-right' },
        { label: 'Center', value: 'center' },
        { label: 'Bottom Left', value: 'bottom-left' }, { label: 'Bottom Center', value: 'bottom-center' }, { label: 'Bottom Right', value: 'bottom-right' },
      ]},
      { key: 'background', label: 'Background', type: 'text' },
      { key: 'padding', label: 'Padding', type: 'number', min: 0, max: 100, step: 4, defaultValue: 16 },
    ],
  },
  // ── Background Removal ─────
  {
    type: 'remove_background',
    category: 'tools',
    subcategory: 'Enhancement',
    displayName: 'Remove Background',
    description: 'Remove image background using AI (BRIA or SAM)',
    icon: 'Eraser',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.imageOut()],
    defaultData: { provider: 'fal', model: 'bria-remove-background' },
    inspectorFields: [
      { key: 'provider', label: 'Provider', type: 'provider_select' },
      { key: 'model', label: 'Model', type: 'model_select' },
    ],
    providerBound: true,
  },
  // ── Enhancement / Upscale ─────
  {
    type: 'upscale',
    category: 'tools',
    subcategory: 'Enhancement',
    displayName: 'Upscale Image',
    description: 'Upscale image resolution using AI (Topaz, Magnific, Recraft)',
    icon: 'Maximize2',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.imageOut()],
    defaultData: { provider: 'fal', model: 'magnific-upscale', scale: 2 },
    inspectorFields: [
      { key: 'provider', label: 'Provider', type: 'provider_select' },
      { key: 'model', label: 'Model', type: 'model_select' },
      { key: 'scale', label: 'Scale Factor', type: 'select', options: [
        { value: '2', label: '2x' }, { value: '4', label: '4x' },
      ] },
    ],
    providerBound: true,
  },
  {
    type: 'inpaint',
    category: 'tools',
    subcategory: 'Enhancement',
    displayName: 'Inpaint (Fill)',
    description: 'Fill masked area with AI-generated content using prompt',
    icon: 'PaintBucket',
    status: 'active',
    inputs: [PORT.imageIn(), PORT.imageIn('mask'), PORT.textIn()],
    outputs: [PORT.imageOut()],
    defaultData: { provider: 'fal', model: 'flux-fill-pro' },
    inspectorFields: [
      { key: 'provider', label: 'Provider', type: 'provider_select' },
      { key: 'model', label: 'Model', type: 'model_select' },
    ],
    providerBound: true,
  },
  // ── Text tools ──────────────
  {
    type: 'prompt_enhancer',
    category: 'tools',
    subcategory: 'Text tools',
    displayName: 'Prompt Enhancer',
    description: 'Enhance prompts using AI',
    icon: 'Sparkles',
    status: 'active',
    inputs: [PORT.textIn()],
    outputs: [PORT.textOut()],
    defaultData: { style: 'detailed', provider: 'fal', model: 'prompt-enhancer' },
    providerBound: true,
  },
  {
    type: 'run_any_llm',
    category: 'tools',
    subcategory: 'Text tools',
    displayName: 'Run Any LLM',
    description: 'Run a prompt through any supported LLM',
    icon: 'Sparkles',
    status: 'active',
    inputs: [PORT.textIn()],
    outputs: [PORT.textOut()],
    defaultData: { provider: 'fal', model: 'run-any-llm', system_prompt: '' },
    providerBound: true,
  },
  {
    type: 'image_describer',
    category: 'tools',
    subcategory: 'Text tools',
    displayName: 'Image Describer',
    description: 'Generate a text description of an image',
    icon: 'FileText',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.textOut()],
    defaultData: { provider: 'fal', model: 'image-describer' },
    providerBound: true,
  },
  {
    type: 'video_describer',
    category: 'tools',
    subcategory: 'Text tools',
    displayName: 'Video Describer',
    description: 'Generate a text description of a video',
    icon: 'FileText',
    status: 'active',
    inputs: [PORT.videoIn()],
    outputs: [PORT.textOut()],
    defaultData: { provider: 'fal', model: 'video-describer' },
    providerBound: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // TOOLS > Iterators
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'text_iterator',
    category: 'tools',
    subcategory: 'Iterators',
    displayName: 'Text Iterator',
    description: 'Iterate over text lines or segments',
    icon: 'Repeat',
    status: 'active',
    inputs: [PORT.textIn()],
    outputs: [PORT.textOut()],
    defaultData: { separator: '\\n' },
  },
  {
    type: 'image_iterator',
    category: 'tools',
    subcategory: 'Iterators',
    displayName: 'Image Iterator',
    description: 'Iterate over a batch of images',
    icon: 'Repeat',
    status: 'active',
    inputs: [{ id: 'images', label: 'Images', kind: 'image', multiple: true }],
    outputs: [PORT.imageOut()],
    defaultData: {},
  },
  {
    type: 'video_iterator',
    category: 'tools',
    subcategory: 'Iterators',
    displayName: 'Video Iterator',
    description: 'Iterate over a batch of videos',
    icon: 'Repeat',
    status: 'active',
    inputs: [{ id: 'videos', label: 'Videos', kind: 'video', multiple: true }],
    outputs: [PORT.videoOut()],
    defaultData: {},
  },

  // ══════════════════════════════════════════════════════════════════════════
  // TOOLS > Helpers
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'router',
    category: 'tools',
    subcategory: 'Helpers',
    displayName: 'Conditional Router',
    description: 'Route input to path A or B based on a condition',
    icon: 'GitBranch',
    status: 'active',
    inputs: [PORT.anyIn()],
    outputs: [PORT.anyOut('output_a'), PORT.anyOut('output_b')],
    defaultData: { condition: 'always_a', condition_value: '' },
    inspectorFields: [
      { key: 'condition', label: 'Condition', type: 'select', options: [
        { label: 'Always A', value: 'always_a' },
        { label: 'Always B', value: 'always_b' },
        { label: 'Input contains...', value: 'contains' },
        { label: 'Input does not contain...', value: 'not_contains' },
        { label: 'Input equals...', value: 'equals' },
        { label: 'Input is not empty', value: 'not_empty' },
        { label: 'Input is empty', value: 'empty' },
      ]},
      { key: 'condition_value', label: 'Value', type: 'text' },
    ],
  },
  {
    type: 'output',
    category: 'tools',
    subcategory: 'Helpers',
    displayName: 'Output',
    description: 'Mark as final output',
    icon: 'CirclePlay',
    status: 'active',
    inputs: [PORT.anyIn()],
    outputs: [],
    defaultData: { save_to_library: true, mark_approved: false },
    inspectorFields: [
      { key: 'save_to_library', label: 'Save to Library', type: 'toggle', defaultValue: true },
      { key: 'mark_approved', label: 'Mark as Approved', type: 'toggle', defaultValue: false },
    ],
  },
  {
    type: 'sticky_note',
    category: 'tools',
    subcategory: 'Helpers',
    displayName: 'Sticky Note',
    description: 'Add a note to the canvas',
    icon: 'StickyNote',
    status: 'active',
    inputs: [],
    outputs: [],
    defaultData: { text: '', color: 'yellow' },
  },
  {
    type: 'depth_anything_v2',
    category: 'tools',
    subcategory: 'Helpers',
    displayName: 'Depth Anything V2',
    description: 'Generate a depth map from an image',
    icon: 'Layers',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.imageOut('depth_map')],
    defaultData: { provider: 'fal', model: 'depth-anything-v2' },
    providerBound: true,
  },
  {
    type: 'compare',
    category: 'tools',
    subcategory: 'Helpers',
    displayName: 'Compare',
    description: 'Compare two images or videos side by side',
    icon: 'ArrowLeftRight',
    status: 'active',
    inputs: [PORT.anyIn('input_a'), PORT.anyIn('input_b')],
    outputs: [],
    defaultData: {},
  },
  {
    type: 'kling_element',
    category: 'tools',
    subcategory: 'Helpers',
    displayName: 'Kling Element',
    description: 'Generate video using Kling Element model',
    icon: 'Sparkles',
    status: 'active',
    inputs: [PORT.imageIn()],
    outputs: [PORT.videoOut()],
    defaultData: { provider: 'fal', model: 'kling-video' },
    providerBound: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // TOOLS > Datatypes
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'number',
    category: 'tools',
    subcategory: 'Datatypes',
    displayName: 'Number',
    description: 'A numeric constant value',
    icon: 'Hash',
    status: 'active',
    inputs: [],
    outputs: [{ id: 'value', label: 'Value', kind: 'any' }],
    defaultData: { value: 0 },
    inspectorFields: [{ key: 'value', label: 'Value', type: 'number' }],
  },
  {
    type: 'text',
    category: 'tools',
    subcategory: 'Datatypes',
    displayName: 'Text',
    description: 'A plain text constant value',
    icon: 'Type',
    status: 'active',
    inputs: [],
    outputs: [PORT.textOut()],
    defaultData: { value: '' },
    inspectorFields: [{ key: 'value', label: 'Text', type: 'textarea' }],
  },
  {
    type: 'toggle',
    category: 'tools',
    subcategory: 'Datatypes',
    displayName: 'Toggle',
    description: 'A boolean on/off switch',
    icon: 'ToggleLeft',
    status: 'active',
    inputs: [],
    outputs: [{ id: 'value', label: 'Value', kind: 'any' }],
    defaultData: { value: false },
    inspectorFields: [{ key: 'value', label: 'Enabled', type: 'toggle' }],
  },
  {
    type: 'list_selector',
    category: 'tools',
    subcategory: 'Datatypes',
    displayName: 'List Selector',
    description: 'Select an item from a predefined list',
    icon: 'List',
    status: 'active',
    inputs: [],
    outputs: [{ id: 'value', label: 'Selected', kind: 'any' }],
    defaultData: { items: [], selected_index: 0 },
  },
  {
    type: 'seed',
    category: 'tools',
    subcategory: 'Datatypes',
    displayName: 'Seed',
    description: 'A seed value for reproducible generation',
    icon: 'Dice3',
    status: 'active',
    inputs: [],
    outputs: [{ id: 'seed', label: 'Seed', kind: 'any' }],
    defaultData: { value: -1, randomize: true },
    inspectorFields: [
      { key: 'value', label: 'Seed', type: 'number', defaultValue: -1 },
      { key: 'randomize', label: 'Randomize', type: 'toggle', defaultValue: true },
    ],
  },
  {
    type: 'array',
    category: 'tools',
    subcategory: 'Datatypes',
    displayName: 'Array',
    description: 'Combine multiple inputs into an array',
    icon: 'StretchHorizontal',
    status: 'active',
    inputs: [PORT.anyIn('item_1'), PORT.anyIn('item_2')],
    outputs: [{ id: 'array', label: 'Array', kind: 'any' }],
    defaultData: {},
  },

  // ══════════════════════════════════════════════════════════════════════════
  // IMAGE MODELS — these are generic generation nodes bound to model catalog
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'image_generator',
    category: 'image_models',
    subcategory: 'Generate from text',
    displayName: 'Image Generator',
    description: 'Generate images from text using AI models',
    icon: 'ImagePlus',
    status: 'active',
    inputs: [PORT.textIn(), PORT.negPromptIn(), PORT.refImageIn(), PORT.brandIn(), PORT.campaignIn(), PORT.productIn()],
    outputs: [PORT.imageOut()],
    defaultData: {
      provider: 'fal',
      model: 'flux-2-pro',
      aspect_ratio: '1:1',
      quality_preset: 'standard',
      style_preset: 'none',
      num_outputs: 1,
      seed: -1,
    },
    inspectorFields: [
      { key: 'provider', label: 'Provider', type: 'provider_select' },
      { key: 'model', label: 'Model', type: 'model_select' },
      { key: 'aspect_ratio', label: 'Aspect Ratio', type: 'select', options: [
        { label: '1:1', value: '1:1' }, { label: '16:9', value: '16:9' }, { label: '9:16', value: '9:16' },
        { label: '4:3', value: '4:3' }, { label: '3:4', value: '3:4' }, { label: '3:2', value: '3:2' },
        { label: '2:3', value: '2:3' }, { label: '21:9', value: '21:9' },
      ]},
      { key: 'quality_preset', label: 'Quality', type: 'select', options: [
        { label: 'Draft', value: 'draft' }, { label: 'Standard', value: 'standard' },
        { label: 'High', value: 'high' }, { label: 'Ultra', value: 'ultra' },
      ]},
      { key: 'style_preset', label: 'Style', type: 'select', options: [
        { label: 'None', value: 'none' }, { label: 'Cinematic', value: 'cinematic' },
        { label: 'Photographic', value: 'photographic' }, { label: 'Anime', value: 'anime' },
        { label: 'Digital Art', value: 'digital_art' }, { label: 'Comic Book', value: 'comic_book' },
        { label: 'Fantasy', value: 'fantasy' }, { label: 'Neon Punk', value: 'neon_punk' },
      ]},
      { key: 'num_outputs', label: 'Outputs', type: 'number', min: 1, max: 4, step: 1, defaultValue: 1 },
      { key: 'seed', label: 'Seed (-1 = random)', type: 'number', defaultValue: -1 },
      { key: 'lora_url', label: 'LoRA URL (optional)', type: 'text' },
      { key: 'lora_scale', label: 'LoRA Scale', type: 'slider', min: 0, max: 1, step: 0.05, defaultValue: 0.8 },
    ],
    providerBound: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // VIDEO MODELS
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'video_generator',
    category: 'video_models',
    subcategory: 'Generate from text or image',
    displayName: 'Video Generator',
    description: 'Generate videos from text/image using AI models',
    icon: 'Video',
    status: 'active',
    inputs: [PORT.textIn(), PORT.negPromptIn(), PORT.refImageIn(), PORT.refVideoIn(), PORT.brandIn(), PORT.campaignIn(), PORT.productIn()],
    outputs: [PORT.videoOut()],
    defaultData: {
      provider: 'fal',
      model: 'wan-2.5',
      duration: 5,
      aspect_ratio: '16:9',
      quality_preset: 'standard',
      motion_strength: 5,
      fps: 24,
    },
    inspectorFields: [
      { key: 'provider', label: 'Provider', type: 'provider_select' },
      { key: 'model', label: 'Model', type: 'model_select' },
      { key: 'duration', label: 'Duration (s)', type: 'select', options: [
        { label: '2s', value: '2' }, { label: '4s', value: '4' }, { label: '5s', value: '5' },
        { label: '6s', value: '6' }, { label: '8s', value: '8' }, { label: '10s', value: '10' },
      ]},
      { key: 'aspect_ratio', label: 'Aspect Ratio', type: 'select', options: [
        { label: '16:9', value: '16:9' }, { label: '9:16', value: '9:16' }, { label: '1:1', value: '1:1' },
      ]},
      { key: 'quality_preset', label: 'Quality', type: 'select', options: [
        { label: 'Draft', value: 'draft' }, { label: 'Standard', value: 'standard' }, { label: 'High', value: 'high' },
      ]},
      { key: 'motion_strength', label: 'Motion', type: 'slider', min: 1, max: 10, step: 1, defaultValue: 5 },
    ],
    providerBound: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // AUDIO MODELS
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'tts',
    category: 'audio_models',
    displayName: 'Text to Speech',
    description: 'Generate speech audio from text (F5-TTS, Kokoro, MiniMax, Dia)',
    icon: 'Mic',
    status: 'active',
    inputs: [PORT.textIn()],
    outputs: [{ id: 'audio', label: 'Audio', kind: 'any' }],
    defaultData: { provider: 'fal', model: 'f5-tts', voice: 'default' },
    inspectorFields: [
      { key: 'provider', label: 'Provider', type: 'provider_select' },
      { key: 'model', label: 'Model', type: 'model_select' },
      { key: 'voice', label: 'Voice', type: 'select', options: [
        { label: 'Default', value: 'default' },
        { label: 'Male 1', value: 'male_1' }, { label: 'Male 2', value: 'male_2' },
        { label: 'Female 1', value: 'female_1' }, { label: 'Female 2', value: 'female_2' },
      ]},
    ],
    providerBound: true,
  },
  {
    type: 'music_generator',
    category: 'audio_models',
    displayName: 'Music / SFX Generator',
    description: 'Generate background music or sound effects from text description',
    icon: 'Music',
    status: 'active',
    inputs: [PORT.textIn()],
    outputs: [{ id: 'audio', label: 'Audio', kind: 'any' }],
    defaultData: { provider: 'fal', model: 'stable-audio', duration: 10 },
    inspectorFields: [
      { key: 'provider', label: 'Provider', type: 'provider_select' },
      { key: 'model', label: 'Model', type: 'model_select' },
      { key: 'duration', label: 'Duration (s)', type: 'number', min: 3, max: 60, step: 1, defaultValue: 10 },
    ],
    providerBound: true,
  },
  {
    type: 'lip_sync',
    category: 'video_models',
    subcategory: 'Lip Sync & Avatar',
    displayName: 'Lip Sync',
    description: 'Sync video with audio for realistic lip movement (OmniHuman, Sync)',
    icon: 'MessageCircle',
    status: 'active',
    inputs: [
      PORT.videoIn(),
      { id: 'audio', label: 'Audio', kind: 'any', required: true },
    ],
    outputs: [PORT.videoOut()],
    defaultData: { provider: 'fal', model: 'omnihuman-v1.5' },
    inspectorFields: [
      { key: 'provider', label: 'Provider', type: 'provider_select' },
      { key: 'model', label: 'Model', type: 'model_select' },
    ],
    providerBound: true,
  },
  {
    type: 'audio_import',
    category: 'quick_access',
    displayName: 'Import Audio',
    description: 'Import an audio file (voice, music, SFX)',
    icon: 'FileAudio',
    status: 'active',
    inputs: [],
    outputs: [{ id: 'audio', label: 'Audio', kind: 'any' }],
    defaultData: { url: '' },
    inspectorFields: [
      { key: 'url', label: 'Audio URL', type: 'text' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // VIDEO EDITING
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'video_trim',
    category: 'tools',
    subcategory: 'Video editing',
    displayName: 'Video Trim / Speed',
    description: 'Trim video start/end and adjust playback speed',
    icon: 'Scissors',
    status: 'active',
    inputs: [PORT.videoIn()],
    outputs: [PORT.videoOut()],
    defaultData: { start_time: 0, end_time: -1, speed: 1.0 },
    inspectorFields: [
      { key: 'start_time', label: 'Start (s)', type: 'number', min: 0, max: 60, step: 0.1, defaultValue: 0 },
      { key: 'end_time', label: 'End (s, -1=all)', type: 'number', min: -1, max: 60, step: 0.1, defaultValue: -1 },
      { key: 'speed', label: 'Speed', type: 'select', options: [
        { label: '0.25x (slow-mo)', value: '0.25' }, { label: '0.5x', value: '0.5' },
        { label: '1x (normal)', value: '1' }, { label: '1.5x', value: '1.5' },
        { label: '2x (fast)', value: '2' },
      ]},
    ],
  },
  {
    type: 'video_transition',
    category: 'tools',
    subcategory: 'Video editing',
    displayName: 'Video Transition',
    description: 'Add transition between two video clips (crossfade, cut, wipe)',
    icon: 'Blend',
    status: 'active',
    inputs: [PORT.videoIn('video_a'), PORT.videoIn('video_b')],
    outputs: [PORT.videoOut()],
    defaultData: { transition_type: 'crossfade', duration: 0.5 },
    inspectorFields: [
      { key: 'transition_type', label: 'Transition', type: 'select', options: [
        { label: 'Cut', value: 'cut' }, { label: 'Crossfade', value: 'crossfade' },
        { label: 'Fade to Black', value: 'fade_black' }, { label: 'Wipe Left', value: 'wipe_left' },
        { label: 'Wipe Right', value: 'wipe_right' },
      ]},
      { key: 'duration', label: 'Duration (s)', type: 'slider', min: 0.1, max: 2, step: 0.1, defaultValue: 0.5 },
    ],
  },
  {
    type: 'storyboard',
    category: 'tools',
    subcategory: 'Video editing',
    displayName: 'Storyboard',
    description: 'Define a multi-shot sequence with scene descriptions, camera, and continuity rules',
    icon: 'LayoutGrid',
    status: 'active',
    inputs: [],
    outputs: [PORT.textOut('shots')],
    defaultData: {
      shots: [
        { scene: 'Opening wide shot', camera: 'static', duration: '3s' },
        { scene: 'Close-up on subject', camera: 'dolly_in', duration: '2s' },
        { scene: 'Reveal product', camera: 'orbit', duration: '3s' },
      ],
    },
    inspectorFields: [
      { key: 'shots', label: 'Shots (JSON)', type: 'textarea' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // CRM NODES
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'brand',
    category: 'crm',
    displayName: 'Brand',
    description: 'Load brand context from CRM',
    icon: 'Palette',
    status: 'active',
    inputs: [],
    outputs: [{ id: 'brand', label: 'Brand Context', kind: 'brand_context' }],
    defaultData: { brand_profile_id: null },
    inspectorFields: [{ key: 'brand_profile_id', label: 'Brand Profile', type: 'select' }],
  },
  {
    type: 'campaign',
    category: 'crm',
    displayName: 'Campaign',
    description: 'Load campaign context from CRM',
    icon: 'Megaphone',
    status: 'active',
    inputs: [],
    outputs: [{ id: 'campaign', label: 'Campaign Context', kind: 'campaign_context' }],
    defaultData: { campaign_id: null },
    inspectorFields: [{ key: 'campaign_id', label: 'Campaign', type: 'select' }],
  },
  {
    type: 'product',
    category: 'crm',
    displayName: 'Product',
    description: 'Load product context from CRM',
    icon: 'Package',
    status: 'active',
    inputs: [],
    outputs: [{ id: 'product', label: 'Product Context', kind: 'product_context' }],
    defaultData: { product_id: null },
    inspectorFields: [{ key: 'product_id', label: 'Product', type: 'select' }],
  },
  {
    type: 'audience',
    category: 'crm',
    displayName: 'Audience',
    description: 'Load audience segment from CRM',
    icon: 'UsersRound',
    status: 'active',
    inputs: [],
    outputs: [{ id: 'audience', label: 'Audience Context', kind: 'audience_context' }],
    defaultData: { audience_id: null },
    inspectorFields: [{ key: 'audience_id', label: 'Audience', type: 'select' }],
  },
  {
    type: 'asset_library',
    category: 'crm',
    displayName: 'Asset Library',
    description: 'Browse and select from CRM asset library',
    icon: 'FolderOpen',
    status: 'active',
    inputs: [],
    outputs: [PORT.anyOut('asset')],
    defaultData: { asset_id: null, asset_type: 'image' },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BUSINESS OUTPUT NODES
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'save_to_assets',
    category: 'output',
    displayName: 'Save to Assets',
    description: 'Save generated output to CRM asset library',
    icon: 'HardDriveDownload',
    status: 'active',
    inputs: [PORT.anyIn()],
    outputs: [],
    defaultData: { folder: '', tags: [], auto_name: true },
    inspectorFields: [
      { key: 'folder', label: 'Folder', type: 'text' },
      { key: 'auto_name', label: 'Auto-name', type: 'toggle', defaultValue: true },
    ],
  },
  {
    type: 'attach_to_campaign',
    category: 'output',
    displayName: 'Attach to Campaign',
    description: 'Attach output to a CRM campaign',
    icon: 'Link',
    status: 'active',
    inputs: [PORT.anyIn(), PORT.campaignIn()],
    outputs: [],
    defaultData: { campaign_id: null },
    inspectorFields: [{ key: 'campaign_id', label: 'Campaign', type: 'select' }],
  },
  {
    type: 'mark_approved',
    category: 'output',
    displayName: 'Mark Approved',
    description: 'Mark output as approved for use',
    icon: 'CheckCircle',
    status: 'active',
    inputs: [PORT.anyIn()],
    outputs: [PORT.anyOut()],
    defaultData: { approved: false, approved_by: null },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // PROCESSING NODES
  // ══════════════════════════════════════════════════════════════════════════
  {
    type: 'style',
    category: 'tools',
    subcategory: 'Helpers',
    displayName: 'Style',
    description: 'Apply a style preset to generation',
    icon: 'Palette',
    status: 'active',
    inputs: [PORT.textIn()],
    outputs: [PORT.textOut()],
    defaultData: { style: 'cinematic' },
    inspectorFields: [
      { key: 'style', label: 'Style', type: 'select', options: [
        { label: 'None', value: 'none' }, { label: 'Cinematic', value: 'cinematic' },
        { label: 'Anime', value: 'anime' }, { label: 'Photographic', value: 'photographic' },
        { label: 'Digital Art', value: 'digital_art' }, { label: 'Comic Book', value: 'comic_book' },
        { label: 'Fantasy', value: 'fantasy' }, { label: 'Neon Punk', value: 'neon_punk' },
        { label: 'Isometric', value: 'isometric' }, { label: 'Pixel Art', value: 'pixel_art' },
      ]},
    ],
  },
];

// ─── Registry helpers ────────────────────────────────────────────────────────

const _registryMap = new Map<string, NodeRegistryEntry>();
NODE_REGISTRY.forEach((entry) => _registryMap.set(entry.type, entry));

export function getNodeDef(type: string): NodeRegistryEntry | undefined {
  return _registryMap.get(type);
}

export function getNodesByCategory(category: string): NodeRegistryEntry[] {
  return NODE_REGISTRY.filter((n) => n.category === category);
}

export function getNodesBySubcategory(category: string, subcategory: string): NodeRegistryEntry[] {
  return NODE_REGISTRY.filter((n) => n.category === category && n.subcategory === subcategory);
}

export function searchNodes(query: string): NodeRegistryEntry[] {
  const q = query.toLowerCase();
  return NODE_REGISTRY.filter(
    (n) =>
      n.displayName.toLowerCase().includes(q) ||
      n.type.toLowerCase().includes(q) ||
      n.description?.toLowerCase().includes(q) ||
      n.subcategory?.toLowerCase().includes(q)
  );
}

// ─── Category display config (for the library UI) ────────────────────────────

export type LibraryCategoryConfig = {
  key: string;
  label: string;
  subcategories?: { key: string; label: string }[];
};

export const LIBRARY_CATEGORIES: LibraryCategoryConfig[] = [
  { key: 'quick_access', label: 'Quick access' },
  {
    key: 'tools',
    label: 'Tools',
    subcategories: [
      { key: 'Editing', label: 'Editing' },
      { key: 'Matte', label: 'Matte' },
      { key: 'Text tools', label: 'Text tools' },
      { key: 'Iterators', label: 'Iterators' },
      { key: 'Helpers', label: 'Helpers' },
      { key: 'Datatypes', label: 'Datatypes' },
    ],
  },
  {
    key: 'image_models',
    label: 'Image models',
    subcategories: [
      { key: 'Generate from text', label: 'Generate from text' },
      { key: 'Generate vector graphics', label: 'Generate vector graphics' },
      { key: 'Edit images', label: 'Edit images' },
      { key: 'Generate from image', label: 'Generate from image' },
      { key: 'Enhance images', label: 'Enhance images' },
    ],
  },
  {
    key: 'video_models',
    label: 'Video models',
    subcategories: [
      { key: 'Generate from text or image', label: 'Generate from text or image' },
      { key: 'Generate from video', label: 'Generate from video' },
      { key: 'Lip sync', label: 'Lip sync' },
      { key: 'Enhance videos', label: 'Enhance videos' },
    ],
  },
  {
    key: '3d_models',
    label: '3D models',
    subcategories: [
      { key: 'Generate from text or image', label: 'Generate from text or image' },
    ],
  },
  {
    key: 'custom_models',
    label: 'Custom models',
    subcategories: [
      { key: 'Community models', label: 'Community models' },
    ],
  },
];

// ─── Context menu mapping (used by right-click on canvas) ────────────────────

export const QUICK_ACCESS_ITEMS = NODE_REGISTRY.filter((n) => n.category === 'quick_access');
